### ISSUE TITLE
Everyone's Silent - Random Bug

### ISSUE THREAD

**Issue by owlboy** [Guribo/BetterAudio#4]
While testing, I had an instance of about seven people, and upon rejoining I could not hear anyone, and non of their nameplates were indicating they were speaking either. They could hear me.

Have you run into this? Is there a workaround? Would it mean the Udon script did not initialize/start properly?

**Comment by Guribo** [comment]
I have not yet experienced this. It happened before that when a player left that the system broke but this got fixed. From what you describe it sounds like the script initializes everone with a range of zero when you join. If you have the UI menu in the world you can test if pressing the reset all button fixes it. If that also doesn't work then the BetterPlayerAudio script has crashed. I will look into it.

**Comment by Guribo** [comment]
I was finally able to have a look at it and I assume you used it without the menu. There was an issue when that is the case. I will update it soon.

**Comment by Guribo** [comment]
Fix will be included in the next release.

**Comment by owlboy** [comment]
Sorry that I have not had time to get back to this, but you were totally right! I was testing without the menu!
