### ISSUE TITLE
wonder how to add voice reverb? saw reverb on readme.......

### ISSUE THREAD

**Issue by xzkeee** [Guribo/BetterAudio#6]

**Comment by Guribo** [comment]
There is no reverb support for voices in this. The reverb is referring to worldaudio sources that are driven by a BetterAudioSource script. This hasn't been released yet as it is in development. There is apparently a way to affect voices too but I don't know yet how.

**Comment by Guribo** [comment]
I did a little research recently regarding voice reverb, these are the results currently: https://github.com/Guribo/BetterAudio/wiki/Reverb-in-VRChat

**Comment by xzkeee** [comment]
big thanks! I will try them out
