### ISSUE TITLE
[Question] - Output player audio into an audio source instead

### ISSUE THREAD

**Issue by lilrad** [Guribo/BetterAudio#9]
Would it be possible to edit the 'BetterPlayerAudio' and respective Overrides scripts to allow player audio to play from an audio source instead? if so what would be the best way to go about doing so.

**Comment by Guribo** [comment]
As far as I know this is not possible. The VRCPlayerApi only allows changing the distances and volumes. You can not decouple the avatar sound effects or voice from the avatar as we have no access to the audio sources.
